feeds:
   - url: "https://www.svtplay.se/bonusfamiljen/rss.xml"
     binary: "svtplay-dl"
     filters: 
     - "syntolkat"
     options: " -f -S -o '/home/joakim/plex/serier/Bonusfamiljen'"
   - url: "https://www.svtplay.se/jordskott/rss.xml"
     binary: "svtplay-dl"
     options: "-f -S -o '/home/joakim/plex/serier/Jordskott'"
   - url: "https://www.svtplay.se/pyjamashjaltarna/rss.xml"
     binary: "svtplay-dl"
     options: " -o '/home/joakim/plex/christoffer/ph2'"
   - url: "https://www.svtplay.se/andys-dinosaurieaventyr/rss.xml"
     binary: "svtplay-dl"
     options: " -o '/home/joakim/plex/christoffer/andys.dinosaurieaventyr'"
   - url: "https://www.svtplay.se/fixarna/rss.xml"
     binary: "svtplay-dl"
     options: " -o '/home/joakim/plex/christoffer/Fixarna'"
   - url: "https://www.svtplay.se/heidi/rss.xml"
     binary: "svtplay-dl"
     options: " -o '/home/joakim/plex/christoffer/Heidi'"
   - url: "https://www.svtplay.se/andys-forhistoriska-aventyr/rss.xml"
     binary: "svtplay-dl"
     options: " -o '/home/joakim/plex/christoffer/andys.fornhistoriska.aventyr'"
   - url: "https://www.svtplay.se/kate-och-mim-mim/rss.xml"
     binary: "svtplay-dl"
     options: " -o '/home/joakim/plex/christoffer/Kate.och.mim-mim'"
   - url: "https://www.svtplay.se/masterflygarna/rss.xml"
     binary: "svtplay-dl"
     options: " -o '/home/joakim/plex/christoffer/Masterflygarna'"
   - url: "https://www.tv4play.se/rss_feeds?nodes=farang"
     binary: "svtplay-dl"
     options: " -f -S -o '/home/joakim/plex/serier/Farang'"
   - url: "https://www.svtplay.se/greta-gris/rss.xml"
     binary: "svtplay-dl"
     options: " -o '/home/joakim/plex/christoffer/Greta.Gris'"
   - url: "https://www.svtplay.se/bron/rss.xml"
     binary: "svtplay-dl"
     options: " -f -S -o '/home/joakim/plex/serier/Bron'"
   - url: "https://www.svtplay.se/octonauterna/rss.xml"
     binary: "svtplay-dl"
     options: " -o '/home/joakim/plex/christoffer/octonauterna'"
   - url: "https://www.svtplay.se/billions/rss.xml"
     binary: "svtplay-dl"
     options: " -S -o '/home/joakim/plex/serier/Billions'"
   - url: "https://www.svtplay.se/helikopterranet/rss.xml"
     binary: "svtplay-dl"
     options: " -f -S -o '/home/joakim/plex/serier/Helikopter'"
   - url: "https://www.svtplay.se/alfons-aberg/rss.xml"
     binary: "svtplay-dl"
     options: " -o '/home/joakim/plex/christoffer/Alfons.Aberg'"
   - url: "https://www.svtplay.se/zorro---legenden-fods/rss.xml"
     binary: "svtplay-dl"
     options: " -o '/home/joakim/plex/christoffer/zorro'"
   - url: "https://www.svtplay.se/experimenten/rss.xml"
     binary: "svtplay-dl"
     options: " -f -S -o '/home/joakim/plex/serier/Exprimenten'"
   - url: "https://www.svtplay.se/grotesco/rss.xml"
     binary: "svtplay-dl"
     options: " -o '/home/joakim/plex/serier/Grotesco'"
   - url: "https://www.svtplay.se/mr-robot/rss.xml"
     binary: "svtplay-dl"
     options: " -S -o '/home/joakim/plex/serier/Mr-Robot'"
   - url: "https://www.tv4play.se/rss_feeds?nodes=enkelst%C3%B6ten"
     binary: "svtplay-dl"
     options: " -S -o '/home/joakim/plex/serier/Enkelstoten'"
   - url: "https://www.svtplay.se/monster/rss.xml"
     binary: "svtplay-dl"
     options: " -S -o '/home/joakim/plex/serier/Monster'"
   - url: "https://www.svtplay.se/kenny-starfighter/rss.xml"
     binary: "svtplay-dl"
     options: " -f -S -o '/home/joakim/plex/christoffer/Kenny-Starfighter'"
   - url: "https://www.svtplay.se/percy-tarar/rss.xml"
     binary: "svtplay-dl"
     options: " -f -S -o '/home/joakim/plex/serier/Percy-Tarar'"
   - url: "https://www.svtplay.se/nilecity-1056/rss.xml"
     binary: "svtplay-dl"
     options: " -f -S -o '/home/joakim/plex/serier/Nile-City'"
   - url: "https://www.svtplay.se/macken/rss.xml"
     binary: "svtplay-dl"
     options: " -f -S -o '/home/joakim/plex/serier/Macken'"
   - url: "https://www.svtplay.se/forsta-dejten/rss.xml"
     binary: "svtplay-dl"
     options: " -f -S -o '/home/joakim/plex/serier/forsta-dejten'"
   - url: "https://www.svtplay.se/mia-och-klara/rss.xml"
     binary: "svtplay-dl"
     options: " -f -S -o '/home/joakim/plex/serier/Mia-och-Klara'"

