feeds:
   - url: "https://www.svtplay.se/var-tid-ar-nu/rss.xml"
     binary: "svtplay-dl"
   #  filters: 
   #    - "syntolkat"
     options: "-f -S -o '/home/joakim/plex/serier/var-tid-ar-nu'"
   - url: "https://www.svtplay.se/morran-och-tobias/rss.xml"
     binary: "svtplay-dl"
     options: "-S -o '/home/joakim/plex/serier/morran.och.tobias'"
#  - url: "https://www.tv4play.se/rss_feeds?nodes=enkelst%C3%B6ten"
#    binary: "svtplay-dl"
#    options: "-S -o '/home/joakim/plex/serier/Enkelstoten'"
   - url: "https://www.svtplay.se/pirater-i-huset-intill/rss.xml"
     binary: "svtplay-dl"
     options: " -f -S -o '/home/joakim/plex/christoffer/pirater-i-huset-intill'"
   - url: "https://www.svtplay.se/labyrint/rss.xml"
     binary: "svtplay-dl"
     options: "-S -o '/home/joakim/plex/christoffer/Labyrint'"
   - url: "https://www.svtplay.se/ranchen/rss.xml"
     binary: "svtplay-dl"
     options: " -f -S -o '/home/joakim/plex/christoffer/ranchen'"
#   - url: "https://www.tv4play.se/rss_feeds?nodes=jul-med-ernst"
#     binary: "svtplay-dl"
#     options: " -f -S -o '/home/joakim/plex/serier/jul-med-ernst'"
   - url: "https://www.svtplay.se/simon/rss.xml"
     binary: "svtplay-dl"
     options: " -f -S -o '/home/joakim/plex/christoffer/simon'"
   - url: "https://www.svtplay.se/rorri-racerbil/rss.xml"
     binary: "svtplay-dl"
     options: " -f -S -o '/home/joakim/plex/christoffer/rorri-racerbil'"

#  - url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCvpNIQlTMpDfR8kv9Z64f5g"
#    filters:
#      - "Babblarna"
   - url: "https://www.svtplay.se/andra-aket/rss.xml"
     binary: "svtplay-dl"
     options: " -f -S -o '/home/joakim/plex/serier/Andra\ aket'"

   - url: "https://www.svtplay.se/mannen-under-trappan/rss.xml"
     binary: "svtplay-dl"
     options: " -f -S -o '/home/joakim/plex/serier/Mannen\ under\ trappan'"

   - url: "https://www.svtplay.se/falsk-identitet/rss.xml"
     binary: "svtplay-dl"
     options: " -f -S -o '/home/joakim/plex/serier/Falsk\ identitet'"

   - url: "https://www.svtplay.se/onda-aningar/rss.xml"
     binary: "svtplay-dl"
     options: " -f -S -o '/home/joakim/plex/serier/Onda\ aningar'"

   - url: "https://www.svtplay.se/kommissarie-bancroft/rss.xml"
     binary: "svtplay-dl"
     options: " -f -S -o '/home/joakim/plex/serier/Kommisarie\ Bancroft'"



